#INCLUDE 'PROTHEUS.CH'
#INCLUDE 'PARMTYPE.CH'

//PONTO DE ENTRADA APOS A INCLUSO DA ORDEM DE PRODUO. QUANDO FOR INCLUSÃO MANUAL, GRAVARÁ
//O CAMPO C2_XORGEM COM 'MANUAL'.
//NUTRIZA - E.L.O. - 11/10/2016.

USER FUNCTION MA650PBAT ()
	Local _Ret	:= ""
	/*IF INCLUI .AND. !ISBLIND()
	RECLOCK('SC2',.F.)
	SC2->C2_XORIGEM	:= 'MANUAL'
	SC2->(MSUNLOCK())
	ENDIF*/

RETURN